### ISSUE TITLE
APKAM: Implement access to keys without namespace

### ISSUE THREAD

**Issue by murali-shris** [atsign-foundation/at_server#1830]
### Is your feature request related to a problem? Please describe.

AbstractVerbHandler.isAuthorized currently checks for access to keys with namespace for an enrollment.
There is no access restriction in place for keys with NO namespace.

### Describe the solution you'd like

1) all apps will have access to special keys e.g ```shared_key.alice@bob, @alice:shared_key@bob ``` 
2) all apps that were authenticated before enrollment will have access to all the keys
3) privileged app/first app with __manage namespace access,  will have access to all the keys
4) enrolled apps will have access to keys without namespace, only if they have * in their namespace list.

**Comment by murali-shris** [comment]
@gkc 2),3) will be covered by existing code. We have to implement 1) and 4)

**Comment by murali-shris** [comment]
Steps involved in running at_client tests against local server branch
1. Install virtual environment in local using the below docker compose file
```
services:
  virtualenv:
    #build: .
    image: atsigncompany/virtualenv:vip
    platform: linux/amd64 //added this line to  use secondary binary built in linux and run on macos arm.
    ports:
      - "127.0.0.1:6379:6379"
      - "64:64"
      - "127.0.0.1:9001:9001"
      - "25000-25017:25000-25017"
    extra_hosts:
      - "vip.ve.atsign.zone:127.0.0.1"
    environment:
      - testingMode=true

  masqdns:
    image: atsigncompany/masqdns:prodvip
    ports:
      - "5380:8080"
      - "54:54/udp"
 ```     
 2. Run pkamLoad script from supervisord http://localhost:9001/
 3. Stop all the instances from supervisord console
 4. Generate secondary binary from local server branch
 ```
 dart compile exe bin/main.dart -o secondary
 ```
 5. Copy the binary to docker container
 ```
 docker cp secondary <container_id>:/atsign/secondary/secondary
 ```
 6. login to docker container and grant execute permission to the binary
 ```
 docker exec -it <container_id> /bin/bash
 chmod 755 /atsign/secondary/secondary
 ```
 7. Restart the instances from supervisord
 8. at_client_sdk/tests/at_functional_test/config/config.yaml
 change url to 'vip.ve.atsign.zone'
 firstAtSign, secondAtSign - any two atsigns listed in supervisord
 Run the functional tests
 9.  at_client_sdk/tests/at_end2end_test/config/config12.yaml --> rename to config.yaml
 change url to 'vip.ve.atsign.zone'
 firstAtSign, secondAtSign,thirdAtSign, fourthAtSign - any 4 atsigns listed in supervisord
 10. key initializer files use AtCredentials.credentialsMap which is generated using github actions. In our local, change these files to use at_demo_data
 at_client_sdk/tests/at_end2end_test/lib/src/at_encryption_key_initializers.dart
 at_client_sdk/tests/at_end2end_test/lib/src/test_initializers.dart
 https://gist.github.com/murali-shris/08b7aaaf1de7ff08aa2ac284e72be6ab
 Run the end2end tests
