### ISSUE TITLE
Modify buzz environment to use env variables to set root server rather than using a different config.yaml inside the Docker image.

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#214]
At present we have a somewhat complex machinery to place the staging environment root server URL into config.yaml and then bundle that file with the secondary server.

We could instead simply `docker service update uuid_secondary --env-add rootServerUrl=root.atsign.wtf` and then subsequently start using more consistent images. (Though we may still choose to apply labels like :prod at different times to different images to control the release cycle).

**Comment by kumarnarendra701** [comment]
@Chris - As per my understanding we need to pass rootServerUrl as env instead of config.yaml. so found a solution to pass env(rootServerUrl=root.atsign.wtf) as runtime in docker-compose on stack deployment but we need some mechanism so that secondaries can use rootServerUrl directly instead of config.yml.

**Comment by cpswan** [comment]
At first the setting will be in the environment and the config.yaml, but once the environment is in place then we can drop it from config.yaml and have the same build for all places.

The line I gave above would work to update the existing services, but you're right @kumarnarendra701 that we also need to update the template for docker-compose.yaml, and all of the existing service definition files (in case we ever need to re-register the services in dev/staging like we needed to yesterday in prod).

**Comment by kumarnarendra701** [comment]
@cpswan - Performed testing on passing root URL to compose file and container.

**cat docker-compose.yml**

```yaml
version: "3.8"

services:
  secondary: 
    image: reg.buzz.do-sf2.atsign.zone/atsigncompany/secondary:dev_env
    command: "-a @ATSIGN -p PORT -s ATSECRET"
    environment:
      **- root_base_url=${root_base_url}**
    deploy:
      placement:
        constraints: [node.role == worker]
      resources:
        limits:
          cpus: '0.25'
          memory: '50M'
        reservations:
                #cpus: '0.01'
          memory: '6M'
    ports:
      - target: PORT
        published: PORT
    volumes:
      - "/gluster/@/secondaries/DIR/NAME:/atsign"
      - "/etc/letsencrypt/live/UUID.buzz.do-sf2.atsign.zone:/atsign/certs"
      - "/atsign/config"
    networks:
      second: {}

networks:
  second:
    external: true
    name: secondaries
```

Stack Deploy command - 
**env root_base_url='root.atsign.wtf'** docker stack deploy  --compose-file docker-compose.yml narendra-test-env  --with-registry-auth

**Docker Service Inspect -**
```
983616bc5b8697a79f5",
                    "Labels": {
                        "com.docker.stack.namespace": "narendra-test-env"
                    },
                    "Args": [
                        "-a",
                        "@narendra-test-env",
                        "-p",
                        "34447",
                        "-s",
                        "88b7cd62c2890539d6778b69eb3ae49d69f181ce8842f02b09974068ad6ab64421b8cd3ef38fb79d29c880f3a7461f257d3d43b17ad7954e39d579439e6b4e94"
                    ],
                    "Env": [
                        **"root_base_url=root.atsign.wtf"**
```
