### ISSUE TITLE
Secondary won't start without config/config.yaml

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#270]
**Describe the bug**
When running with `dart run --observe` the secondary pauses due to exception:

```
paused by exception at AtSecondaryConfig.notificationQuarantineDuration (at_secondary_config.dart:550:29)
```

In this code block:

```dart
  static int? get notificationQuarantineDuration {
    var result = _getIntEnvVar('notificationQuarantineDuration');
    if (result != null) {
      return _getIntEnvVar('notificationQuarantineDuration');
    }
    if (ConfigUtil.getYaml()!['notification'] != null &&
        ConfigUtil.getYaml()!['notification']['quarantineDuration'] != null) {
      return ConfigUtil.getYaml()!['notification']['quarantineDuration'];
    }
    return _notificationQuarantineDuration;
  }
```

**To Reproduce**
1. Cloned this repo and did `dart pub get && dart pub update` in the at_persistence_secondary_server and at_secondary_server directories
2. Tared up the storage directory and certs for a dess atsign and extracted them to ./storage and ./certs directories.
3. `dart run --observe [path_to_secondary/bin/main.dart] -a [myatsign] -p [port] -s [secret]` using parameters from ~atsign/dess/[myatsign]/docker-compose.yaml 
4. If I create ./config/config.yaml using [path_to_secondary/config/config.yaml] the secondary will start (as [notification:][quarantineDuration: 10] is expressed.

```yaml
notification:
  autoNotify: true
  max_entries: 5
  # The maximum number of retries for a notification.
  max_retries: 5
  # The quarantine duration of an atsign.
  quarantineDuration: 10
  # The job frequency
  jobFrequency: 5
```

**Expected behavior**
Secondary should start with production defaults without the need for a config.yaml

**Screenshots**
![image](https://user-images.githubusercontent.com/478926/129367253-a676b945-9ebc-4f86-b5e5-722aa98f801e.png)
