### ISSUE TITLE
Error code 'forwarding'

### ISSUE THREAD

**Issue by gkc** [atsign-foundation/at_server#509]
**Describe the bug**
* In the case where a client makes a request to server A, and an exception is thrown in server A because of an error response from server B, we should try to preserve error codes where they make sense in the response to the ultimate client
  * For example: Client calls plookup on Server A; Server A  calls lookup on Server B; server B returns "error:AT0015-Key not found : ..."
  ```
  @sitaram@lookup:phone@murali
  error:null-null : Request to remote secondary @murali at vip.ve.atsign.zone:7001 received error
    response 'error:AT0015-key not found : @sitaram:phone@murali does not exist in keystore'
  ```
  * Server A will currently throw an AtConnectException with the error response it got from B, providing the additional information that it came from B
    * The "null-null" is caused by https://github.com/atsign-foundation/at_tools/issues/152

**Expected behaviour**
  * When returning to the client we would like to preserve that AT0015 (key not found) as it is most correct, but provide the additional context of the full error message from the other end. For example:
  ```
     @sitaram@lookup:phone@murali
     error:AT0015-key not found : Request to remote secondary @murali at vip.ve.atsign.zone:7001 received error
       response 'error:AT0015-key not found : @sitaram:phone@murali does not exist in keystore'
  ```
  * This can be achieved in outbound_message_listener, for example, by having it
    * When there's an error code from remote server, inspect it and match it to its corresponding AtException
      * If there is a matching Exception then throw that, adding the entire message received from remote
      * Else do what's being done now (throw AtConnectException)
  * Consider extending at_commons error_message.dart with a way to create (not throw, just create) the correct exception given an error code. (We currently have mapping from exception to error-code but not the other way around)

**Comment by gkc** [comment]
@kalluriramkumar As per our discussion. If you want to pick this one up, please assign yourself and go ahead!

**Comment by sitaram-kalluri** [comment]
The changes are completed in the following PR: https://github.com/atsign-foundation/at_server/pull/841

Spent 5 SP and carry forward to update the unit tests. Adding 3 SP to rewrite the tests as mentioned the PR

**Comment by murali-shris** [comment]
Dependent issue 
https://github.com/atsign-foundation/at_server/issues/691

**Comment by sitaram-kalluri** [comment]
The changes are merged to trunk branch: [json_encode_error_message](https://github.com/atsign-foundation/at_server/pull/850)

**Comment by gkc** [comment]
@kalluriramkumar is this ticket complete, should it be closed?

**Comment by sitaram-kalluri** [comment]
@gkc : The changes are yet to released into canary. Hence the ticket is open. 

Currently facing issue in releasing code to canary. Following is the issue:

```
Run sed -i '0,/version/ s/version\:.*/&+${GITHUB_REF#refs/tags/}/' pubspec.yaml
  sed -i '0,/version/ s/version\:.*/&+${GITHUB_REF#refs/tags/}/' pubspec.yaml
  shell: /usr/bin/bash -e {0}
  env:
    working-directory: at_server
    VERSION: c3.0.[2](https://github.com/atsign-foundation/at_server/actions/runs/3082036906/jobs/4981321618#step:4:2)[3](https://github.com/atsign-foundation/at_server/actions/runs/3082036906/jobs/4981321618#step:4:3)c
sed: -e expression #1, char [4](https://github.com/atsign-foundation/at_server/actions/runs/3082036906/jobs/4981321618#step:4:4)[7](https://github.com/atsign-foundation/at_server/actions/runs/3082036906/jobs/4981321618#step:4:8): unknown option to `s'
```

The same command works fine in e2e_test_prep action.

The reason we did this change is because, we have version package added in pubspec.yaml in at_secondary_server. So when updating the version of at_secondary_server, the version of the `version` package is also getting updated causing the `dart pub get` to fail. The fix I did is look for first occurrence of version and then append the github action's run number.

Link to github actions run: https://github.com/atsign-foundation/at_server/actions/runs/3082036906/jobs/4981321618
