### ISSUE TITLE
Few of the secondaries failed to upgrade to a latest version

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_server#606]
**Describe the bug**
Shepherd fails to upgrade few of the secondaries to latest version

Following are the couple of atsign's which are running on the older version of secondary server
1. dying36dragonfly
2. zathura97tall

**Expected behavior**
The secondaries should be running on the latest version.

**Additional context**
Logs snippet of secondary running on old version:

```
c7410742-7f82-53ec-b9a6-47adb6d2d4e6_secondary.1.uspgj5suhtcb@swarm0001-09.us-central1-c.c.secondaries.internal    | 
c7410742-7f82-53ec-b9a6-47adb6d2d4e6_secondary.1.uspgj5suhtcb@swarm0001-09.us-central1-c.c.secondaries.internal    | INFO|2022-03-27 12:10:46.559582|AtSecondaryServer|Secondary server started on version : 3.0.10 on root server : root.atsign.org
```
Stats verb result:
```
----------------------------
@dying36dragonfly@stats:7
data: [{"id":"7","name":"secondaryServerVersion","value":"3.0.10"}]
```

**Comment by cpswan** [comment]
dying36dragonfly was migrated from hornet to swarm0001 in the last week, so it should have picked up the latest secondary image

**Comment by cpswan** [comment]
shepherd isn't running on swarm0001

**Comment by cpswan** [comment]
I just grabbed /root/shepherd.yaml from horent-01:

```yaml
version: "3"

services:
  shepherd:
    image: reg.hornet.atsign.zone/atsigncompany/shepherd:latest
    extra_hosts:
      - "reg.hornet.atsign.zone:10.164.0.7"
    environment:
      TZ: 'US/PST'
      SLEEP_TIME: '1h'
      VERBOSE: 'true'
      FILTER_SERVICES: 'label=com.docker.stack.image=reg.hornet.atsign.zone/atsigncompany/secondary:prod'
      WITH_REGISTRY_AUTH: 'true'
      IMAGE_AUTOCLEAN_LIMIT: 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/root/.docker/config.json
    deploy:
      placement:
        constraints:
          - node.role == manager
```

Then ran:

```
docker stack deploy --compose-file shepherd.yaml --with-registry-auth shepherd
```
