### ISSUE TITLE
testingMode environment variable set but not used

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_server#793]
**Describe the bug**

In #777 we introduced the `testingMode` env variable in two places within `.github/workflows/at_server.yaml`:

```yaml
     # setting new env var "testingMode" to true. Needed for some of the functional tests to pass.
    env:
      testingMode: true
```

```yaml
        run: docker run -d --rm --name at_virtual_env_cont -e testingMode="true" -p 6379:6379 -p 25000-25017:25000-25017 -p 64:64 at_virtual_env:trunk
```

But only the second block will actually pass an env variable to the test container, the first block simply sets the env for the GitHub actions runner.

We could have used:

```yaml
        run: docker run -d --rm --name at_virtual_env_cont -e testingMode="${testingMode}" -p 6379:6379 -p 25000-25017:25000-25017 -p 64:64 at_virtual_env:trunk
```

But since there's no condition that would set it false that just obscures what's happening

**Expected behavior**

We only set the env to be passed to the container (second block) and don't set env for the GitHub actions runner where it has no effect.
