### ISSUE TITLE
Github actions fails to push secondary server canary image.

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/at_server#932]
**Describe the bug**
The github actions in the secondary server fails to when pushing the secondary server canary image. Following is the link to the github action failue: https://github.com/atsign-foundation/at_server/actions/runs/3082036906/jobs/4981321618

Error snippet:
```
Run sed -i '0,/version/ s/version\:.*/&+${GITHUB_REF#refs/tags/}/' pubspec.yaml
  sed -i '0,/version/ s/version\:.*/&+${GITHUB_REF#refs/tags/}/' pubspec.yaml
  shell: /usr/bin/bash -e {0}
  env:
    working-directory: at_server
    VERSION: c3.0.[2](https://github.com/atsign-foundation/at_server/actions/runs/3082036906/jobs/4981321618#step:4:2)[3](https://github.com/atsign-foundation/at_server/actions/runs/3082036906/jobs/4981321618#step:4:3)c
sed: -e expression #1, char [4](https://github.com/atsign-foundation/at_server/actions/runs/3082036906/jobs/4981321618#step:4:4)[7](https://github.com/atsign-foundation/at_server/actions/runs/3082036906/jobs/4981321618#step:4:8): unknown option to `s'
 
```
Root cause of the failure:

we have `version` package added in pubspec.yaml in at_secondary_server as a part of JSON encoding the error responses. In github actions, when updating the version of at_secondary_server, the version of `version` package is also getting updated causing the dart pub get to fail. 

In order to fix the issue, added logic in at_server work flow to look for first occurrence of version and then append github action's run number. 
Link to PR's : https://github.com/atsign-foundation/at_server/pull/850/files -  Change in at_server file.

Similar changes are done in other parts in at_server where the `version` attribute is being updated: https://github.com/atsign-foundation/at_server/pull/928/files
